package com.dhanuk.debtbro.util

/**
 * Simple UI string localizer for key app strings.
 * Maps language codes to translated strings for navigation tabs, screen titles, and common buttons.
 *
 * Usage:
 * - Synchronous: `LocalizedString.get(key, langCode)` - pass language code directly
 * - Default: `LocalizedString.getDefault(key)` - falls back to English
 */
object LocalizedString {

    private var currentLang = "en"

    fun setLanguage(code: String) { currentLang = code }

    private val strings = mapOf(
        "en" to mapOf(
            "nav_home" to "Home",
            "nav_debts" to "Debts",
            "nav_split" to "Split",
            "nav_stats" to "Stats",
            "all_debts" to "All Debts",
            "settings" to "Settings",
            "add_debt" to "Add Debt",
            "search_debts" to "Search by name or reason...",
            "they_owe_me" to "💰 They Owe Me",
            "i_owe_them" to "😅 I Owe Them",
            "overdue" to "Overdue 🔥",
            "recent_debts" to "Recent Debts 🕒",
            "see_all" to "See All",
            "leaderboard" to "Debt Leaderboard 🏆",
            "add_payment" to "Add Payment",
            "settle_all" to "Settle All",
            "export_image" to "Export as Image Card",
            "share_whatsapp" to "Share to WhatsApp",
            "payment_history" to "Payment History",
            "no_payments" to "No payments recorded yet.",
            "edit_debt" to "Edit Debt",
            "delete_debt" to "Delete Debt?",
            "delete_confirm" to "This will permanently delete this debt and all its payments. This cannot be undone.",
            "split_bill" to "Split Bill",
            "financial_insights" to "Financial Insights",
            "monthly_trend" to "Monthly Lending Trend",
            "ai_take" to "🤖 AI Financial Take",
            "nudge" to "🤖 BroBot Nudge",
            "total_owed" to "Total Owed to Me",
            "i_owe" to "I Owe",
            "recovery" to "Recovery Rate",
            "settled" to "All-time Settled",
            "net_balance" to "Net Balance",
            "most_trusted" to "🏅 Most Trusted",
            "worst_offender" to "💀 Worst Offender",
            "no_active" to "No active debts. Peaceful wallet!",
            "no_results" to "No results found",
            "try_different" to "Try a different name or keyword",
            "no_debts" to "No debts here!",
            "empty_owed" to "You're either rich or lonely. Add a debt to start.",
            "gentle_reminder" to "Gentle Reminder",
            "settlement_request" to "Settlement Request",
            "payment_due" to "Payment Due",
            "payment_reminder" to "Payment Reminder",
            "delete" to "Delete",
            "cancel" to "Cancel",
            "remaining_balance" to "Remaining Balance",
            "debt_settled" to "Debt Settled",
            "paid" to "Paid",
            "total" to "Total",
            "amount" to "Amount",
            "note_optional" to "Note (optional)",
            "save_payment" to "Save Payment",
            "person_name" to "Person Name",
            "total_amount" to "Total Amount",
            "description" to "Description",
            "emoji" to "Emoji",
            "update_debt" to "Update Debt",
            "greeting" to "Hey",
            "money_memory_subtitle" to "Your money memory is sharp today",
            "cloud_sync" to "☁️ Cloud Sync",
            "cloud_sync_desc" to "Sign in with Google to keep your data safe. Even if you change phones, your broke friends can't hide.",
            "go_to_settings" to "Go to Settings",
            "maybe_later" to "Maybe later",
            "total_owed_to_me" to "Total Owed to Me",
            "recovery_rate" to "Recovery Rate",
            "owed_to_me" to "Owed to Me",
            "all_time_settled" to "All-time Settled",
            "debt_recovery_rate" to "Debt Recovery Rate",
            "tap_refresh" to "Tap refresh to get a brutally honest analysis of your finances.",
            "whats_this_for" to "What's this for?",
            "goa_trip_placeholder" to "e.g. Goa Trip, Pizza Party",
            "per_person" to "Split Share",
            "among_people" to "among {count} people",
            "create_split" to "Create Split",
            "past_splits" to "Past Splits",
            "add_person" to "Add Person",
            "name_placeholder" to "Name",
            "ai_take_short" to "AI Take",
            "create_debts" to "Create Debts",
            "select_contact" to "Select Contact",
            "search_contacts" to "Search contacts...",
            "contact_permission_msg" to "Contact permission is needed to pick from your contacts list.",
            "grant_permission" to "Grant Permission",
            "account" to "Account",
            "preferences" to "Preferences",
            "display_name" to "Your Display Name",
            "default_currency" to "Default Currency",
            "nudge_roast_level" to "Nudge Roast Level",
            "data_export" to "Data & Export",
            "export_csv" to "Export to CSV",
            "export_csv_subtitle" to "Download all debts as a spreadsheet",
            "clear_settled" to "Clear Settled Debts",
            "clear_settled_subtitle" to "Permanently delete fully paid debts",
            "clear_settled_dialog" to "Clear Settled Debts?",
            "clear_settled_dialog_desc" to "This will permanently delete all settled debts. This cannot be undone.",
            "delete_all" to "Delete All",
            "language" to "Language",
            "select_language" to "Select Language",
            "regenerate" to "Regenerate",
            "watch_ad" to "Watch Ad",
            "later" to "Later",
            "free_regenerations_used" to "🎯 Free Regenerations Used!",
            "free_regenerations_desc" to "You've used all {count} free regenerations. Watch a short ad to earn more!",
        ),
        "hi" to mapOf(
            "nav_home" to "होम",
            "nav_debts" to "कर्ज़",
            "nav_split" to "बाँटें",
            "nav_stats" to "आँकड़े",
            "all_debts" to "सभी कर्ज़",
            "settings" to "सेटिंग्स",
            "add_debt" to "कर्ज़ जोड़ें",
            "search_debts" to "नाम या कारण से खोजें...",
            "they_owe_me" to "💰 मुझे देना है",
            "i_owe_them" to "😅 मैं owe करता हूँ",
            "overdue" to "समय बीत गया 🔥",
            "recent_debts" to "हाल के कर्ज़ 🕒",
            "see_all" to "सभी देखें",
            "leaderboard" to "कर्ज़ लीडरबोर्ड 🏆",
            "add_payment" to "भुगतान जोड़ें",
            "settle_all" to "सभी चुकाएं",
            "export_image" to "इमेज के रूप में भेजें",
            "share_whatsapp" to "WhatsApp पर भेजें",
            "payment_history" to "भुगतान इतिहास",
            "no_payments" to "कोई भुगतान नहीं।",
            "edit_debt" to "कर्ज़ संपादित करें",
            "delete_debt" to "कर्ज़ हटाएं?",
            "delete_confirm" to "यह कर्ज़ और सभी भुगतान स्थायी रूप से हटा दिए जाएंगे।",
            "split_bill" to "बिल बाँटें",
            "financial_insights" to "वित्तीय अंतर्दृष्टि",
            "monthly_trend" to "मासिक लेनदेन",
            "ai_take" to "🤖 AI राय",
            "nudge" to "🤖 ब्रोबॉट नज",
            "total_owed" to "मुझे देना है",
            "i_owe" to "मैं देता हूँ",
            "recovery" to "वसूली दर",
            "settled" to "सभी चुकाए गए",
            "net_balance" to "नेट बैलेंस",
            "most_trusted" to "🏅 सबसे भरोसेमंद",
            "worst_offender" to "💀 सबसे बड़ा डिफॉल्टर",
            "no_active" to "कोई कर्ज़ नहीं। शांति!",
            "no_results" to "कोई परिणाम नहीं",
            "try_different" to "दूसरा नाम या कीवर्ड आज़माएं",
            "no_debts" to "यहाँ कोई कर्ज़ नहीं!",
            "empty_owed" to "कोई कर्ज़ नहीं। नया जोड़ें।",
            "gentle_reminder" to "विनम्र अनुस्मारक",
            "settlement_request" to "भुगतान अनुरोध",
            "payment_due" to "भुगतान बाकी",
            "payment_reminder" to "भुगतान अनुस्मारक",
            "delete" to "हटाएं",
            "cancel" to "रद्द करें",
            "remaining_balance" to "शेष राशि",
            "debt_settled" to "कर्ज़ चुकाया गया",
            "paid" to "भुगतान",
            "total" to "कुल",
            "amount" to "राशि",
            "note_optional" to "नोट (वैकल्पिक)",
            "save_payment" to "भुगतान सहेजें",
            "person_name" to "व्यक्ति का नाम",
            "total_amount" to "कुल राशि",
            "description" to "विवरण",
            "emoji" to "इमोजी",
            "update_debt" to "कर्ज़ अपडेट करें",
            "greeting" to "नमस्ते",
            "money_memory_subtitle" to "आज आपका वित्तीय स्मरण शक्ति तेज़ है",
            "cloud_sync" to "☁️ क्लाउड सिंक",
            "cloud_sync_desc" to "Google से साइन इन करें ताकि आपका डेटा सुरक्षित रहे।",
            "go_to_settings" to "सेटिंग्स में जाएं",
            "maybe_later" to "शायद बाद में",
            "total_owed_to_me" to "मुझे देना है कुल",
            "recovery_rate" to "वसूली दर",
            "owed_to_me" to "मुझे देना है",
            "all_time_settled" to "सभी चुकाए गए",
            "debt_recovery_rate" to "कर्ज़ वसूली दर",
            "tap_refresh" to "वित्तीय विश्लेषण के लिए रिफ्रेश करें।",
            "whats_this_for" to "यह किसलिए?",
            "goa_trip_placeholder" to "जैसे गोआ ट्रिप, पिज़्ज़ा पार्टी",
            "per_person" to "प्रति व्यक्ति हिस्सा",
            "among_people" to "{count} लोगों में",
            "create_split" to "बाँटें बनाएं",
            "past_splits" to "पिछले बंटवारे",
            "add_person" to "व्यक्ति जोड़ें",
            "name_placeholder" to "नाम",
            "ai_take_short" to "AI राय",
            "create_debts" to "कर्ज़ बनाएं",
            "select_contact" to "संपर्क चुनें",
            "search_contacts" to "संपर्क खोजें...",
            "contact_permission_msg" to "संपर्क चुनने के लिए अनुमति आवश्यक है।",
            "grant_permission" to "अनुमति दें",
            "account" to "खाता",
            "preferences" to "प्राथमिकताएं",
            "display_name" to "आपका नाम",
            "default_currency" to "मुद्रा",
            "nudge_roast_level" to "नज स्तर",
            "data_export" to "डेटा और निर्यात",
            "export_csv" to "CSV निर्यात",
            "export_csv_subtitle" to "सभी कर्ज़ डाउनलोड करें",
            "clear_settled" to "चुकाए गए कर्ज़ हटाएं",
            "clear_settled_subtitle" to "सभी चुकाए गए कर्ज़ हटाएं",
            "clear_settled_dialog" to "चुकाए गए कर्ज़ हटाएं?",
            "clear_settled_dialog_desc" to "सभी चुकाए गए कर्ज़ स्थायी रूप से हटा दिए जाएंगे।",
            "delete_all" to "सभी हटाएं",
            "language" to "भाषा",
            "select_language" to "भाषा चुनें",
            "regenerate" to "पुनः जनरेट",
            "watch_ad" to "विज्ञापन देखें",
            "later" to "बाद में",
            "free_regenerations_used" to "🎯 मुफ्त जनरेशन समाप्त!",
            "free_regenerations_desc" to "आपने सभी {count} मुफ्त जनरेशन उपयोग कर लिए हैं।",
        ),
        "es" to mapOf(
            "nav_home" to "Inicio",
            "nav_debts" to "Deudas",
            "nav_split" to "Dividir",
            "nav_stats" to "Estadísticas",
            "all_debts" to "Todas las Deudas",
            "settings" to "Ajustes",
            "add_debt" to "Agregar Deuda",
            "search_debts" to "Buscar por nombre o razón...",
            "they_owe_me" to "💰 Me Deben",
            "i_owe_them" to "😅 Les Debo",
            "overdue" to "Vencido 🔥",
            "recent_debts" to "Deudas Recientes 🕒",
            "see_all" to "Ver Todo",
            "leaderboard" to "Tabla de Deudores 🏆",
            "add_payment" to "Agregar Pago",
            "settle_all" to "Liquidar Todo",
            "export_image" to "Exportar como Imagen",
            "share_whatsapp" to "Compartir en WhatsApp",
            "payment_history" to "Historial de Pagos",
            "no_payments" to "Sin pagos registrados.",
            "split_bill" to "Dividir Cuenta",
            "financial_insights" to "Perspectiva Financiera",
            "monthly_trend" to "Tendencia Mensual",
            "ai_take" to "🤖 Opinión IA",
            "nudge" to "🤖 BroBot Aviso",
            "total_owed" to "Me Deben",
            "i_owe" to "Debo",
            "recovery" to "Tasa de Recuperación",
            "settled" to "Liquidado Total",
            "net_balance" to "Balance Neto",
            "no_active" to "Sin deudas activas.",
            "delete" to "Eliminar",
            "cancel" to "Cancelar",
            "remaining_balance" to "Saldo Restante",
            "debt_settled" to "Deuda Liquidada",
            "paid" to "Pagado",
            "total" to "Total",
            "amount" to "Monto",
            "note_optional" to "Nota (opcional)",
            "save_payment" to "Guardar Pago",
            "person_name" to "Nombre",
            "total_amount" to "Monto Total",
            "description" to "Descripción",
            "emoji" to "Emoji",
            "update_debt" to "Actualizar Deuda",
            "greeting" to "Hola",
            "money_memory_subtitle" to "Tu memoria financiera está afilada hoy",
            "cloud_sync" to "☁️ Sincronización",
            "cloud_sync_desc" to "Inicia sesión con Google para mantener tus datos seguros.",
            "go_to_settings" to "Ir a Ajustes",
            "maybe_later" to "Quizás luego",
            "total_owed_to_me" to "Me Deben Total",
            "recovery_rate" to "Tasa de Recuperación",
            "owed_to_me" to "Me Deben",
            "all_time_settled" to "Liquidado Total",
            "debt_recovery_rate" to "Tasa de Recuperación",
            "tap_refresh" to "Toca actualizar para un análisis financiero.",
            "whats_this_for" to "¿Para qué es?",
            "goa_trip_placeholder" to "ej. Viaje a Goa, Fiesta de pizza",
            "per_person" to "Por Persona",
            "among_people" to "entre {count} personas",
            "create_split" to "Crear División",
            "past_splits" to "Divisiones Anteriores",
            "add_person" to "Agregar Persona",
            "name_placeholder" to "Nombre",
            "ai_take_short" to "Opinión IA",
            "create_debts" to "Crear Deudas",
            "select_contact" to "Seleccionar Contacto",
            "search_contacts" to "Buscar contactos...",
            "contact_permission_msg" to "Se necesita permiso de contactos.",
            "grant_permission" to "Dar Permiso",
            "account" to "Cuenta",
            "preferences" to "Preferencias",
            "display_name" to "Tu Nombre",
            "default_currency" to "Moneda",
            "nudge_roast_level" to "Nivel de Nudge",
            "data_export" to "Datos y Exportación",
            "export_csv" to "Exportar CSV",
            "export_csv_subtitle" to "Descargar todas las deudas",
            "clear_settled" to "Limpiar Liquidadas",
            "clear_settled_subtitle" to "Eliminar deudas liquidadas",
            "clear_settled_dialog" to "¿Limpiar Deudas Liquidadas?",
            "clear_settled_dialog_desc" to "Esto eliminará permanentemente todas las deudas liquidadas.",
            "delete_all" to "Eliminar Todo",
            "language" to "Idioma",
            "select_language" to "Seleccionar Idioma",
            "regenerate" to "Regenerar",
            "watch_ad" to "Ver Anuncio",
            "later" to "Luego",
            "free_regenerations_used" to "🎯 Regeneraciones Gratis Usadas!",
            "free_regenerations_desc" to "Has usado todas las {count} regeneraciones gratis.",
        ),
        "fr" to mapOf(
            "nav_home" to "Accueil",
            "nav_debts" to "Dettes",
            "nav_split" to "Partager",
            "nav_stats" to "Statistiques",
            "all_debts" to "Toutes les Dettes",
            "settings" to "Paramètres",
            "add_debt" to "Ajouter Dette",
            "search_debts" to "Rechercher par nom ou motif...",
            "they_owe_me" to "💰 On Me Doit",
            "i_owe_them" to "😅 Je Dois",
            "overdue" to "En Retard 🔥",
            "recent_debts" to "Dettes Récentes 🕒",
            "see_all" to "Voir Tout",
            "leaderboard" to "Classement 🏆",
            "add_payment" to "Ajouter Paiement",
            "settle_all" to "Tout Régler",
            "export_image" to "Exporter en Image",
            "share_whatsapp" to "Partager sur WhatsApp",
            "payment_history" to "Historique des Paiements",
            "no_payments" to "Aucun paiement enregistré.",
            "split_bill" to "Partager l'Addition",
            "financial_insights" to "Analyse Financière",
            "monthly_trend" to "Tendance Mensuelle",
            "ai_take" to "🤖 Avis IA",
            "nudge" to "🤖 BroBot Rappel",
            "total_owed" to "On Me Doit",
            "i_owe" to "Je Dois",
            "recovery" to "Taux de Récupération",
            "settled" to "Total Réglé",
            "net_balance" to "Balance Nette",
            "no_active" to "Aucune dette active.",
            "delete" to "Supprimer",
            "cancel" to "Annuler",
            "remaining_balance" to "Solde Restant",
            "debt_settled" to "DeRéglée",
            "paid" to "Payé",
            "total" to "Total",
            "amount" to "Montant",
            "note_optional" to "Note (optionnel)",
            "save_payment" to "Enregistrer",
            "person_name" to "Nom",
            "total_amount" to "Montant Total",
            "description" to "Description",
            "emoji" to "Emoji",
            "update_debt" to "Mettre à Jour",
            "greeting" to "Salut",
            "money_memory_subtitle" to "Votre mémoire financière est vive aujourd'hui",
            "cloud_sync" to "☁️ Synchronisation",
            "cloud_sync_desc" to "Connectez-vous avec Google pour garder vos données en sécurité.",
            "go_to_settings" to "Aller aux Paramètres",
            "maybe_later" to "Peut-être plus tard",
            "total_owed_to_me" to "On Me Doit Total",
            "recovery_rate" to "Taux de Récupération",
            "owed_to_me" to "On Me Doit",
            "all_time_settled" to "Total Réglé",
            "debt_recovery_rate" to "Taux de Récupération",
            "tap_refresh" to "Appuyez pour une analyse financière.",
            "whats_this_for" to "Pour quoi faire?",
            "goa_trip_placeholder" to "ex. Voyage à Goa, Fête pizza",
            "per_person" to "Par Personne",
            "among_people" to "entre {count} personnes",
            "create_split" to "Créer Partage",
            "past_splits" to "Partages Antérieurs",
            "add_person" to "Ajouter Personne",
            "name_placeholder" to "Nom",
            "ai_take_short" to "Avis IA",
            "create_debts" to "Créer Dettes",
            "select_contact" to "Sélectionner Contact",
            "search_contacts" to "Rechercher contacts...",
            "contact_permission_msg" to "Permission de contacts nécessaire.",
            "grant_permission" to "Donner Permission",
            "account" to "Compte",
            "preferences" to "Préférences",
            "display_name" to "Votre Nom",
            "default_currency" to "Devise",
            "nudge_roast_level" to "Niveau BroBot",
            "data_export" to "Données et Export",
            "export_csv" to "Exporter CSV",
            "export_csv_subtitle" to "Télécharger toutes les dettes",
            "clear_settled" to "Effacer Réglées",
            "clear_settled_subtitle" to "Supprimer dettes réglées",
            "clear_settled_dialog" to "Effacer Dettes Réglées?",
            "clear_settled_dialog_desc" to "Cela supprimera définitivement toutes les dettes réglées.",
            "delete_all" to "Supprimer Tout",
            "language" to "Langue",
            "select_language" to "Sélectionner Langue",
            "regenerate" to "Régénérer",
            "watch_ad" to "Regarder Pub",
            "later" to "Plus tard",
            "free_regenerations_used" to "🎯 Régénérations Gratuites Épuisées!",
            "free_regenerations_desc" to "Vous avez utilisé toutes les {count} régénérations gratuites.",
        ),
        "de" to mapOf(
            "nav_home" to "Startseite",
            "nav_debts" to "Schulden",
            "nav_split" to "Teilen",
            "nav_stats" to "Statistiken",
            "all_debts" to "Alle Schulden",
            "settings" to "Einstellungen",
            "add_debt" to "Schuld Hinzufügen",
            "search_debts" to "Suche nach Name oder Grund...",
            "they_owe_me" to "💰 Man Schuldet Mir",
            "i_owe_them" to "😅 Ich Schulde",
            "overdue" to "Überfällig 🔥",
            "recent_debts" to "Aktuelle Schulden 🕒",
            "see_all" to "Alle Anzeigen",
            "leaderboard" to "Rangliste 🏆",
            "add_payment" to "Zahlung Hinzufügen",
            "settle_all" to "Alle Begleichen",
            "export_image" to "Als Bild Exportieren",
            "share_whatsapp" to "Auf WhatsApp Teilen",
            "payment_history" to "Zahlungsverlauf",
            "no_payments" to "Keine Zahlungen erfasst.",
            "split_bill" to "Rechnung Teilen",
            "financial_insights" to "Finanzanalyse",
            "monthly_trend" to "Monatlicher Trend",
            "ai_take" to "🤖 KI-Meinung",
            "nudge" to "🤖 BroBot Erinnerung",
            "total_owed" to "Man Schuldet Mir",
            "i_owe" to "Ich Schulde",
            "recovery" to "Wiederholungsrate",
            "settled" to "Beglichen Gesamt",
            "net_balance" to "Netto-Balance",
            "no_active" to "Keine aktiven Schulden.",
            "delete" to "Löschen",
            "cancel" to "Abbrechen",
            "remaining_balance" to "Restbetrag",
            "debt_settled" to "Schuld Beglichen",
            "paid" to "Bezahlt",
            "total" to "Gesamt",
            "amount" to "Betrag",
            "note_optional" to "Notiz (optional)",
            "save_payment" to "Zahlung Speichern",
            "person_name" to "Name",
            "total_amount" to "Gesamtbetrag",
            "description" to "Beschreibung",
            "emoji" to "Emoji",
            "update_debt" to "Schuld Aktualisieren",
            "greeting" to "Hallo",
            "money_memory_subtitle" to "Deine finanzielle Erinnerung ist heute scharf",
            "cloud_sync" to "☁️ Synchronisierung",
            "cloud_sync_desc" to "Melde dich mit Google an, um deine Daten sicher zu halten.",
            "go_to_settings" to "Zu Einstellungen",
            "maybe_later" to "Vielleicht später",
            "total_owed_to_me" to "Man Schuldet Mir Gesamt",
            "recovery_rate" to "Wiederholungsrate",
            "owed_to_me" to "Man Schuldet Mir",
            "all_time_settled" to "Beglichen Gesamt",
            "debt_recovery_rate" to "Schuldenrückgewinnung",
            "tap_refresh" to "Tippe für eine Finanzanalyse.",
            "whats_this_for" to "Wofür ist das?",
            "goa_trip_placeholder" to "z.B. Goa Reise, Pizza Party",
            "per_person" to "Pro Person",
            "among_people" to "unter {count} Personen",
            "create_split" to "Teilung Erstellen",
            "past_splits" to "Frühere Teilungen",
            "add_person" to "Person Hinzufügen",
            "name_placeholder" to "Name",
            "ai_take_short" to "KI-Meinung",
            "create_debts" to "Schulden Erstellen",
            "select_contact" to "Kontakt Auswählen",
            "search_contacts" to "Kontakte suchen...",
            "contact_permission_msg" to "Kontaktberechtigung ist erforderlich.",
            "grant_permission" to "Berechtigung Erteilen",
            "account" to "Konto",
            "preferences" to "Einstellungen",
            "display_name" to "Dein Name",
            "default_currency" to "Währung",
            "nudge_roast_level" to "BroBot Stufe",
            "data_export" to "Daten & Export",
            "export_csv" to "CSV Exportieren",
            "export_csv_subtitle" to "Alle Schulden herunterladen",
            "clear_settled" to "Begliche Löschen",
            "clear_settled_subtitle" to "Beglichene Schulden löschen",
            "clear_settled_dialog" to "Beglichene Schulden Löschen?",
            "clear_settled_dialog_desc" to "Dies wird alle beglichenen Schulden dauerhaft löschen.",
            "delete_all" to "Alle Löschen",
            "language" to "Sprache",
            "select_language" to "Sprache Wählen",
            "regenerate" to "Neu Generieren",
            "watch_ad" to "Werbung Ansehen",
            "later" to "Später",
            "free_regenerations_used" to "🎯 Freie Generierungen Aufgebraucht!",
            "free_regenerations_desc" to "Du hast alle {count} freien Generierungen verbraucht.",
        ),
        "ja" to mapOf(
            "nav_home" to "ホーム",
            "nav_debts" to "借金",
            "nav_split" to "分割",
            "nav_stats" to "統計",
            "all_debts" to "すべての借金",
            "settings" to "設定",
            "add_debt" to "借金を追加",
            "search_debts" to "名前または理由で検索...",
            "they_owe_me" to "💰 借りがある",
            "i_owe_them" to "😅 借りがある",
            "overdue" to "期限切れ 🔥",
            "recent_debts" to "最近の借金 🕒",
            "see_all" to "すべて表示",
            "leaderboard" to "ランキング 🏆",
            "add_payment" to "支払いを追加",
            "settle_all" to "すべて精算",
            "export_image" to "画像としてエクスポート",
            "share_whatsapp" to "WhatsAppで共有",
            "payment_history" to "支払い履歴",
            "no_payments" to "支払い記録なし。",
            "split_bill" to "割り勘",
            "financial_insights" to "財務インサイト",
            "monthly_trend" to "月間推移",
            "ai_take" to "🤖 AIの見解",
            "nudge" to "🤖 BroBot通知",
            "total_owed" to "借りがある合計",
            "i_owe" to "私が借りている",
            "recovery" to "回収率",
            "settled" to "精算済み合計",
            "net_balance" to "純資産",
            "no_active" to "アクティブな借金なし。",
            "delete" to "削除",
            "cancel" to "キャンセル",
            "remaining_balance" to "残高",
            "debt_settled" to "精算済み",
            "paid" to "支払い済み",
            "total" to "合計",
            "amount" to "金額",
            "note_optional" to "メモ (任意)",
            "save_payment" to "支払いを保存",
            "person_name" to "名前",
            "total_amount" to "合計金額",
            "description" to "説明",
            "emoji" to "絵文字",
            "update_debt" to "借金を更新",
            "greeting" to "こんにちは",
            "money_memory_subtitle" to "今日のあなたの財務記憶は鋭いです",
            "cloud_sync" to "☁️ クラウド同期",
            "cloud_sync_desc" to "Googleでログインしてデータを安全に保ちましょう。",
            "go_to_settings" to "設定へ移動",
            "maybe_later" to "また後で",
            "total_owed_to_me" to "借りがある合計",
            "recovery_rate" to "回収率",
            "owed_to_me" to "借りがある",
            "all_time_settled" to "精算済み合計",
            "debt_recovery_rate" to "債務回収率",
            "tap_refresh" to "財務分析を更新するにはタップ。",
            "whats_this_for" to "何のため？",
            "goa_trip_placeholder" to "例：ゴア旅行、ピザパーティー",
            "per_person" to "1人あたり",
            "among_people" to "{count}人で分割",
            "create_split" to "分割を作成",
            "past_splits" to "過去の分割",
            "add_person" to "人を追加",
            "name_placeholder" to "名前",
            "ai_take_short" to "AIの見解",
            "create_debts" to "借金を作成",
            "select_contact" to "連絡先を選択",
            "search_contacts" to "連絡先を検索...",
            "contact_permission_msg" to "連絡先の選択には許可が必要です。",
            "grant_permission" to "許可を与える",
            "account" to "アカウント",
            "preferences" to "設定",
            "display_name" to "表示名",
            "default_currency" to "通貨",
            "nudge_roast_level" to "BroBotレベル",
            "data_export" to "データとエクスポート",
            "export_csv" to "CSVエクスポート",
            "export_csv_subtitle" to "すべての借金をダウンロード",
            "clear_settled" to "精算済み削除",
            "clear_settled_subtitle" to "精算済みの借金を削除",
            "clear_settled_dialog" to "精算済みの借金を削除？",
            "clear_settled_dialog_desc" to "精算済みの借金は完全に削除されます。",
            "delete_all" to "すべて削除",
            "language" to "言語",
            "select_language" to "言語を選択",
            "regenerate" to "再生成",
            "watch_ad" to "広告を見る",
            "later" to "後で",
            "free_regenerations_used" to "🎯 無料再生成を使い切り!",
            "free_regenerations_desc" to "無料再生成を{count}回すべて使用しました。",
        ),
    )

    fun get(key: String): String {
        return strings[currentLang]?.get(key)
            ?: strings["en"]?.get(key)
            ?: key
    }

    fun get(key: String, langCode: String): String {
        return strings[langCode]?.get(key)
            ?: strings["en"]?.get(key)
            ?: key
    }

    fun getDefault(key: String): String {
        return strings["en"]?.get(key) ?: key
    }
}
